server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#设置feign客户端超时时间（OpebFeign默认支持ribbon）
ribbon:
#指的是建立连接所用的时间，使用与网络状况正常的状态下，两端连接所用的时间
  ReadTimeout: 5000
#指的是建立连接后从服务器读取可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    #feign以什么级别的日志打印
    com.vinzune.springcloud.service.PaymentFeignService: debug