server:
  port: 9275
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: myGateway_route
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    fetch-registry: true
  instance:
    appname: cloud-gateway-service
