server:
  port: 3344
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ZWJman/cloud2020_vinzune.git
          search-paths:
            - springcloud-config
      lable: master