server:
  port: 8001


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: payment8001
    prefer-ip-address: true
spring:
  application:
    name: cloud-provider-hystrix-payment
feign:
  hystrix:
    enabled: true
